### ISSUE TITLE
The figure are small

### ISSUE THREAD

**Issue by simoncchu** [stevekm/IGV-snapshot-automator#5] opened 2017-09-29 03:14 UTC
Hi,

I find this is a really useful tool. However, when I run it on my server, the generated figures are very small.

![image](https://user-images.githubusercontent.com/3340363/30999365-cc4907d0-a4a2-11e7-805a-34a889120d42.png)

Any reason for this? Thank you!

**Comment by stevekm** [comment] 2017-09-29 11:46
Small in what way? Is it not producing the desired height?

However I have also noticed that the width of my own snapshots generated this way suddenly decreased one day and has remained that way for some time. I haven't had time to investigate it much, but I guessed it was likely some quirk with the virtual X11 window it's being rendered into. If I get a chance I'll try to look into it more. Thanks for letting me know that it's not just me!

**Comment by Reedwarbler** [comment] 2017-09-29 12:13
The size of the figure is 640 x 408. I think it is very small.

**Comment by Reedwarbler** [comment] 2017-09-29 13:28
Tried to add parameters "-screen 1 1024x768x24" to "xvfb-run", but still didn't change the output. 

Also notice one warning "Xlib:  extension "RANDR" missing on display ":99".", 
and one error: "ERROR [2017-09-29 09:14:13,089]  [CommandListener.java:141] [Thread-7]  java.net.BindException: Address already in use"

But the screenshot is generated, just the size is default 640x408.

**Comment by stevekm** [comment] 2017-10-11 05:12
Did you try adding the `-ht` argument to the script to increase the height? As you suggest, I think there will probably need to be some sort of parameter passed to xvfb but I have not had time to look into it. But at the very least you should be able to make the image longer this way.

**Comment by CharlesARoy** [comment] 2020-01-02 19:12
Hello, 

I am excited by the potential of this tool, but I am also finding that the images generated are a little small (and oddly zoomed in). Unlike your images, mine don't show the full IGV window. As you suggested, I've tried playing with the height command, but it doesn't seem to have an effect on the generated png any more. 

![chr1_713167_714758_h1000](https://user-images.githubusercontent.com/46253001/71686336-c2145480-2d4f-11ea-9f39-9e23508550cb.png)

**Comment by stevekm** [comment] 2020-01-02 19:41
@CharlesARoy I am not able to debug this at the moment but I suspect that this may be due to whatever the default size & resolution is set to for your system's Xvfb. A few minutes on Google brought me a couple threads that might be helpful in adjusting this;

- Xvfb server manual page: https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml

- passing of Xvfb server args to the xvfb-run script: https://stackoverflow.com/questions/22913794/setting-a-resolution-for-xvfb-run-and-wkhtmltopdf-wkhtmltoimage

- discussion about the annoyance of tiny default Xvfb window size: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=871925

I am not sure how soon I will be able to get around to trying some of these options, but if you feel like trying it yourself the relevant lines of code in the Python script that would need to be adjusted should be here:

https://github.com/stevekm/IGV-snapshot-automator/blob/d32f17893c261f2eb2b671291bec168dcb5a62be/make_IGV_snapshots.py#L239-L240

**Comment by CharlesARoy** [comment] 2020-01-02 21:23
@stevekm Thanks for the fast response.

Per the links (and some others I looked up), I tested a ton of variations of:
`xvfb-run --server-args="-screen 0 1024x768x24"...`
Including:
 `xvfb-run --server-args='-screen 0 1024x768x24'...` (because use of double quotes was messing with the syntax)
`xvfb-run --server-args='-screen 0, 1024x768x24'...` (because some posts said a comma was needed after the 0)
`xvfb-run --server-args='-screen 1 1024x768x24'...`(because some posts suggested using a different screen number)
`xvfb-run --server-args=':1 -screen 0 1024x768x24'...` 
`xvfb-run --server-args=':1 -screen 0, 1024x768x24'...`
`xvfb-run --server-args='-screen 0 2048x1536x8'...` (to try a different resolution and depth)

as well as many similar permutations on the `igv_command = "(Xvfb :{} -screen 0 1600x1200x24 java -Xmx{}m -jar {} -b {}".format(x_serv_port, memMB, igv_jar, igv_script)` line.

In most cases the code ran just fine, but the output looked identical to that produced by your original code.

**Comment by stevekm** [comment] 2020-11-24 17:34
if this is still an issue you might consider trying out `igv-reports` instead; https://github.com/igvteam/igv-reports

**Comment by stevekm** [comment] 2021-07-09 13:52
I am going to close this one since its my understanding that this is caused by the X11 and `xvfb` settings on your system, see the links I posted for possible solutions. If you need anything else feel free to re-open and ping me, thanks

**Closed by stevekm** 2021-07-09 13:52 UTC
Labels: can't fix :(

**Comment by zxclovezby** [comment] 2022-08-22 09:37
> --server-args=

Hello, I want to know how your centerline is added？I tried some parameters, but none of them worked：）

**Comment by CharlesARoy** [comment] 2022-08-30 01:33
@zxclovezby unfortunately I no longer have access to the server where I was running IGV and haven't used it in quite some time. Hopefully you can find something by digging around in the IGV settings.
