### ISSUE TITLE
Only output IGV_snapshots.bat without *png

### ISSUE THREAD

**Issue by zhangzhiyangcs** [stevekm/IGV-snapshot-automator#24] opened 2021-07-29 05:33 UTC
Hi,
    I meet the error when I run IGV-snapshot with comand: python IGV-snapshot-automator-master/make_IGV_snapshots.py   -r  test.bed   -o igv  -g  ./genome.fa  -mem 64000 -s test.bam. There were no error. My bam file size is 80GB.
   But when I just extract bam files with positon in test.bed. It works and output *png. Why cause this? Thanke you.

**Comment by stevekm** [comment] 2021-09-09 14:36
Hi, I am not clear what exactly the problem is? You are not getting any PNG outputs in the first case? Note that your .bed file must contain coordinates for the script to work; if you inspect the .bat file you will see that its simple instructing IGV to take snapshots at the regions in the .bed file. So if the .bed file is empty, there will be no instructions in .bat to take snapshots. Let me know if this helps.

**Comment by stevekm** [comment] 2022-07-25 17:54
closing this one, let me know if you need any more help, thanks

**Closed by stevekm** 2022-07-25 17:54 UTC
